apiVersion: v1
entries:
  owl:
  - apiVersion: v2
    appVersion: v0.5.7
    created: "2023-03-22T01:47:17.772775+08:00"
    description: Message provider
    digest: c184b93ea48bb01eafff4ff27a2e52a104f07d65e822f6c45dfcf178cb268a44
    keywords:
    - owl
    - message
    - email
    - sms
    name: owl
    type: application
    urls:
    - owl-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: v0.5.7
    created: "2023-03-22T01:47:17.7722307+08:00"
    description: Message provider
    digest: d06d6216fa773701e0c06954ea8acf95a200217afc3da0506420356eda7fca4b
    keywords:
    - owl
    - message
    - email
    - sms
    name: owl
    type: application
    urls:
    - owl-0.1.2.tgz
    version: 0.1.2
generated: "2023-03-22T01:47:17.7717071+08:00"
